## RStudio Shortcut Keys {#RStudioShortcutKeys}

汇总：郭沫然   
更新于：2024-12-16


| Console ||     |
|----|----|----|
| **Description**   | **Windows**  | **Mac** |
| 将光标定位到控制台| Ctrl+2    | Ctrl+2 |
| 在历史命令中导航  | Up/Down   | Up/Down |
| **Source** ||     |
| **Description**   | **Windows**  | **Mac** |
| 保存当前文件      | Ctrl+S    | Command+S  |
| 插入块  | Ctrl+Alt+I| Command+Option+I     |
| 运行当前/被选中的代码    | Ctrl+Enter| Command+Enter |
| 再次运行以前区域  | Ctrl+Shift+P | Command+Shift+P      |
| 运行当前文件      | Ctrl+Alt+R| Command+Option+R     |
| 运行当前函数定义代码     | Ctrl+Alt+F| Command+Option+F     |
| 运行当前代码块    | Ctrl+Alt+C| Command+Option+C |
| 运行下一个代码块  | Ctrl+Alt+N| Command+Option+N     |
| 执行一个外部文件中的代码 | Ctrl+Shift+O | Command+Shift+O |
| 切换tab | Ctrl+Alt+Down| Ctrl+Option+Down     |
| Reindent lines    | Ctrl+I    | Command+I  |
| 注释/取消注释 当前行/选中区域 | Ctrl+Shift+C | Command+Shift+C |
| Reflow comment    | Ctrl+Shift+/ | Command+Shift+/      |
| Transpose Letters | Ctrl+T    |    |
| 查找并替换 | Ctrl+F    | Command+F  |
| 查找下一个 | Win: F3, Linux: Ctrl+G     | Command+G  |
| 查找上一个 | Win: Shift+F3,      | Command+Shift+G      |
| 替换并查找 | Ctrl+=    | Command+=  |
| **Editing (Console and Source)**||     |
| **Description**   | **Windows**  | **Mac** |
| 撤销    | Ctrl+Z    | Command+Z  |
| 重复上次撤销的操作  | Ctrl+Shift+Z | Command+Shift+Z      |
| 剪切    | Ctrl+X    | Command+X  |
| 复制    | Ctrl+C    | Command+C  |
| 粘贴    | Ctrl+V    | Command+V  |
| 全选    | Ctrl+A    | Command+A  |
| 删除行  | Ctrl+D    | Command+D  |
| 选择    | Shift+[Arrow]  | Shift+[Arrow]   |
| 选择一个词 | Ctrl+Shift+Left/Right | Option+Shift+Left/Right   |
| 缩进    | Tab (at beginning of line) |     |
| 取消缩进| Shift+Tab | Shift+Tab  |
| 查看光标处的函数帮助     | F1 | F1  |
| 自动完成| Tab or Ctrl+Space   | Tab or Command+Space  |
